package testSteps;

import junit.framework.TestCase;

import testSteps.TestRuner.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;

import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;
import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
public class TestRunerTest extends TestCase {

	public void test_type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertThat(TestRuner.class, notNullValue());
	}

	public void test_instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		TestRuner target = new TestRuner();
		assertThat(target, notNullValue());
	}

}
